root: true
extends: standard
rules:
  no-param-reassign: error
  no-shadow: error
  semi:
    - error
    - always
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  comma-dangle:
    - error
    - arrays: never
      objects: never
      imports: never
      exports: never
      functions: never

